name: streamlit
dependencies:
  - python
  - pip
  - pip:
    - pandas
    - python-dotenv
    - streamlit==1.32.2
    - boto3
    - ipykernel
    - vaderSentiment
    - plotly==5.19.0
    - scikit-learn
    - seaborn